# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-07 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='bio',
            field=models.TextField(default=1, max_length=400),
            preserve_default=False,
        ),
    ]
