# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-04 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('department', models.CharField(choices=[('BFS', 'Biomedical and Forensic Sciences'), ('EBE', 'Engineering and the Built Environment'), ('CTG', 'Computing and Technology'), ('LS', 'Life Sciences'), ('PS', 'Psychology')], max_length=50)),
                ('content', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
